# Generated by Django 2.2.16 on 2022-01-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20220127_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
